[Feat] supports scraping Rio Grande Half Marathon and 5k
contains some eprintlns that I added to track down this error:

error: invalid line 6: Error: webdriver returned error: Element <div id="split" class="MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input"> is not clickable at point (978,418) because another element <div id="menu-" class="MuiPopover-root"> obscures it

However, with the eprintlns in place, it ran successfully.  This makes me
think that I need to wait for visibility before doing a click and that the
eprintlns added enough delay for me to get lucky.